import mongoose from 'mongoose'

const auditLogSchema = new mongoose.Schema(
  {
    user: { type: String, required: true, trim: true, index: true },
    role: {
      type: String,
      enum: ['Admin', 'Super Admin', 'Teacher', 'Staff', 'Student', 'Parent'],
      required: true,
      index: true,
    },
    action: {
      type: String,
      enum: [
        'LOGIN',
        'LOGOUT',
        'STUDENT_CREATE',
        'STUDENT_UPDATE',
        'STUDENT_DELETE',
        'COURSE_CREATE',
        'COURSE_UPDATE',
        'COURSE_DELETE',
        'ATTENDANCE_MARK',
        'ATTENDANCE_UPDATE',
        'ATTENDANCE_DELETE',
        'GRADE_CREATE',
        'GRADE_UPDATE',
        'GRADE_DELETE',
        'SETTINGS_CHANGE',
        'REPORT_EXPORT',
        'DOCUMENT_UPLOAD',
        'DOCUMENT_DELETE',
        'NOTIFICATION_CREATE',
        'NOTIFICATION_READ',
        'NOTIFICATION_DELETE',
        'ADMIN_CREATE',
        'ADMIN_UPDATE',
        'ADMIN_STATUS_CHANGE',
        'ADMIN_ROLE_CHANGE',
        'ADMIN_PASSWORD_RESET',
        'ADMIN_DELETE',
        'DEPARTMENT_CREATE',
        'DEPARTMENT_UPDATE',
        'DEPARTMENT_DELETE',
        'PROGRAM_CREATE',
        'PROGRAM_UPDATE',
        'PROGRAM_DELETE',
        'ACADEMIC_YEAR_CREATE',
        'ACADEMIC_YEAR_UPDATE',
        'ACADEMIC_YEAR_DELETE',
        'SEMESTER_CREATE',
        'SEMESTER_UPDATE',
        'SEMESTER_DELETE',
        'STAFF_CREATE',
        'STAFF_UPDATE',
        'STAFF_DELETE',
        'STUDENT_COURSE_ENROLL',
        'STUDENT_COURSE_UPDATE',
        'STUDENT_COURSE_DELETE',
        'COURSE_ASSIGNMENT_CREATE',
        'COURSE_ASSIGNMENT_UPDATE',
        'COURSE_ASSIGNMENT_DELETE',
        'FEE_CATEGORY_CREATE',
        'FEE_CATEGORY_UPDATE',
        'FEE_CATEGORY_DELETE',
        'FEE_STRUCTURE_CREATE',
        'FEE_STRUCTURE_UPDATE',
        'FEE_STRUCTURE_DELETE',
        'STUDENT_FEE_ASSIGN',
        'FEE_PAYMENT_CREATE',
        'FEE_RECEIPT_CREATE',
        'ROOM_CREATE',
        'ROOM_UPDATE',
        'ROOM_DELETE',
        'TIMETABLE_SLOT_CREATE',
        'TIMETABLE_SLOT_UPDATE',
        'TIMETABLE_SLOT_DELETE',
        'EXAM_CREATE',
        'EXAM_UPDATE',
        'EXAM_DELETE',
        'EXAM_SCHEDULE_CREATE',
        'EXAM_SCHEDULE_UPDATE',
        'EXAM_SCHEDULE_DELETE',
        'HALL_TICKET_GENERATE',
        'EXAM_RESULT_CREATE',
        'EXAM_RESULT_UPDATE',
        'EXAM_RESULT_PUBLISH',
        'ASSIGNMENT_CREATE',
        'ASSIGNMENT_UPDATE',
        'ASSIGNMENT_DELETE',
        'ASSIGNMENT_SUBMIT',
        'ASSIGNMENT_GRADE',
        'LEARNING_MATERIAL_CREATE',
        'LEARNING_MATERIAL_UPDATE',
        'LEARNING_MATERIAL_DELETE',
      ],
      required: true,
      index: true,
    },
    module: {
      type: String,
      enum: [
        'Auth',
        'Students',
        'Courses',
        'Attendance',
        'Grades',
        'Settings',
        'Reports',
        'Documents',
        'Notifications',
        'Admins',
        'Departments',
        'Programs',
        'AcademicYears',
        'Semesters',
        'Staff',
        'StudentCourses',
        'CourseAssignments',
        'Fees',
        'FeeCategories',
        'FeeStructures',
        'StudentFees',
        'FeePayments',
        'FeeReceipts',
        'Rooms',
        'Timetable',
        'Exams',
        'ExamSchedules',
        'ExamResults',
        'HallTickets',
        'Assignments',
        'AssignmentSubmissions',
        'LearningMaterials',
      ],
      required: true,
      index: true,
    },
    description: { type: String, required: true, trim: true },
    ipAddress: { type: String, trim: true, default: '' },
    browser: { type: String, trim: true, default: 'Unknown' },
    device: { type: String, trim: true, default: 'Unknown' },
    metadata: { type: mongoose.Schema.Types.Mixed, default: {} },
    timestamp: { type: Date, default: Date.now, index: true },
  },
  { timestamps: true },
)

auditLogSchema.index({ user: 'text', description: 'text', action: 'text', module: 'text' })
auditLogSchema.index({ role: 1, module: 1, timestamp: -1 })

export const AuditLog = mongoose.model('AuditLog', auditLogSchema)
